language: python
python:
- '2.7'
before_script:
- yes | python setup.py install
- git clone https://github.com/uc-cdis/dictionaryutils; cd dictionaryutils
script:
- "./run_tests.sh"
deploy:
  provider: s3
  access_key_id: AKIAZRNPHKJIJU73ZJ5J
  secret_access_key:
    secure: OudJKjcWEI/HnCOsQzgAKLtTBy8+8K9GzWJfOU02oO3FA2sGPmwDZEwwwxfhcZtKk9NTah+zFMDuFCNa+LC0Ars8EioqpWgpzYQd9AMprDtW+4vpsl5zPAPYlG6CDycWCDyWgrKeFO1DiAuq+DSUkgJYxGOH+1EzmrXmfZNGa1k7ETNYK7aT/X4XpgADwA3OtfOy94w149EtO6oAVVOFaVc2FIYDcVZXzWvUzHx5kYpxbeVhVX1LKdI/cEYodBs05CSv0a3Nf8dkeOZMtfEiO3l+Fk7YlpuwA/8ChXeOfN1mMKyJc5xMP1dB+7aZHs/kSCSCgiyipbGuP7GclJn46+97bUGjh0KzSZTjg7kIoOv9XMkAwFMQGr1gHp2YQr9yiczTmoTseAidp1gveMYztAyNLkS9fKBRIIfEcIp/5lk4mzBNUu77vdb04UePsyBLZzvsPnZfAGtkGBu6iwfGF7ZbFm0Pz3opMW5UroThrhGjWUHqoZ/cuaF97PcDPSufVe/ZWUzcX/Mg7MLPbsQV8zZOvfIlk6GkOYbVweu6CbNtDwV17mmrQTDgKmwuAI85n22yQx08d+tXTi24F9yCRqYDKDKWvDv2/TT3dMs2yOhzBjYt+WyMuZIqI8sG72TAK9v+lUx/WB4jRju6of6e1w3iWu2Yh1MzdbrGrfM34OY=
  bucket: dictionary-artifacts
  local-dir: artifacts
  upload-dir: rerf_dictionary/$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    repo: uc-cdis/rerf_dictionary
    all_branches: true
